language: node_js
node_js: "9"
matrix:
  include:
  - os: windows
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
install:
- nvm install 9
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
branches:
  only:
- master